language: en_core_webs_md
pipeline: supervised_embeddings
policies:
- name: AugmentedMemoizationPolicy
- name: KerasPolicy
  epochs: 50
  max_history: 20
- name: MappingPolicy
#- name: TwoStageFallbackPolicy
#  nlu_threshold: 0.05
#  core_threshold: 0.0
#  fallback_nlu_action_name: "action_default_fallback"
#  deny_suggestion_intent_name: "out_of_scope"
