language: en
pipeline: supervised_embeddings
policies:
- name: AugmentedMemoizationPolicy
- name: KerasPolicy
  epochs: 100
  max_history: 15
- name: MappingPolicy
#- name: TwoStageFallbackPolicy
  #nlu_threshold: 0.05
  #core_threshold: 0.0
  #fallback_nlu_action_name: "action_default_fallback"
  #deny_suggestion_intent_name: "out_of_scope"
