conversension_car = {
    "greet": ["hi", "hello", "Hello!"],
    "ask_for_quote": ["i need a quote, please"],
    "choose_number_3": ["Car, Home & Building Insurance"],
    "give_name": ["Barney Gills"],
    "choose_thrid-party_fire_theft":["Third-party, fire and theft car insurance"],
    "give_email":["Barney@gmail.com"],
    "give_tel":["083 123 4567"],
    "give_id":["890616 0135 008"],
    "give_logbook":["uploading file"],
    "affirm":["yes"],
    "give_address":["36 Bever Hights, Carltonville, Port Elizabeth"],
    "accept_offer":["I Accept this quote, sign me up!"],
    "give_name_bank":["Nedbank"],
    "give_name_account":["B.Gills"],
    "give_account_number":["1223334444"],
    "give_branch_code":["198 765"],
    "give_type_account":["Cheque Account"],
    "give_date":["28th"],
    "goodbye":["No, that’s it. Thanks! Bye"]
}

conversension_id = {
    "investment_money":["I want to investment my money today"],
    "give_name":["Kelly Mars"],
    "give_id":["651006 5864 078"],
    "give_tel":["084 565 7863"],
    "give_email":["kelly@gmail.com"],
    "affirm-0":["yes, I am"],
    "choose_retirement":["G"],
    "choose_plan_of_3_years":["3 years"],
    "choose_take_sustancial_risk":["D"],
    "choose_moderate_risk":["C"],
    "choose_equites":["Equities"],
    "choose_high_capital":["high capital"],
    "choose_two_funds":["I would like to spread it into two funds"],
    "affirm-1":["yes"],
    "choose_monthly_amount":["monthly"],
    "give_money_amount":["R1000 per month"],
    "give_date":["1 st"],
    "give_name_bank":["Nedbank"],
    "give_name_account":["B.Gills"],
    "give_account_number":["1223334444"],
    "give_branch_code":["198 765"],
    "affirm-2":["yes"],
    "deny":["no"]
}

conversension_quick_quote = {
    "ask_for_quick_quote":["Get a quick quote"],
    "affirm-0":["I accept"],
    "give_tel":["076 869 1449"],
    "give_otp":["1588"],
    "give_id":["651006 5864 078"],
    "give_name":["Lisa Muir"],
    "choose_contents":["Contents"],
    "affirm-1":["yes"],
    "give_address":["30 Joan avenue, La Montagne, Pretoria, 0184, South Africa"],
    "say_rent":["I rent it"],
    "affirm-2":["Yes I do"],
    "give_rommates_amount":["one rommates"],
    "give_money_amount":["R100,000.00"],
    "choose_residencial_propuse":["Residential purposes"],
    "choose_townhouse":["Townhouse"],
    "deny-0":["Nope, it’s not"],
    "choose_brick":["Brick"],
    "choose_tile":["Tile"],
    "choose_complex":["Complex"],
    "choose_access_controlled":["Access controlled"],
    "affirm-3":["Yes there is"],
    "deny-1":["No there’s not"],
    "choose_metal_windows":["Metal on all windows"],
    "affirm-4":["yes"],
    "choose_brick_walls":["Brick wall"],
    "choose_lower_1.8":["Lower than 1.8 meters"],
    "choose_security_gate":["With a security gate"],
    "deny-2":["No I haven’t"],
    "choose_one_month_or_less":["One month or less"],
    "deny-3":["No"],
    "deny-4":["No"],
    "deny-5":["No"],
    "deny-6":["No"],
    "deny-7":["No"],
    "choose_proceed_with_quote":["Proceed with the quote"],
    "deny-8":["No"]
}
